project:
  type: book

book:
  title: "Paradigma TISE"
  subtitle: "Paradigma, Metodologi, dan Hirarki Rekayasa"
  author: "Armein Z R Langi"
  date: "24/04/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Paradigma, Metodologi, dan Hirarki Rekayasa"
      chapters: 
        - isi.qmd
    - part: "TISE Level 0: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd
    - part: "TISE Level 1: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd
 
    - part: "TISE Level 2: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd
 
    - part: "TISE Level 3: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd
 
    - part: "TISE Level 4: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd
 
    - part: "TISE Level 5: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd
 
    - part: "TISE Level 6: Rekayasa Energi, Materi, dan Informasi"
      chapters:
        - chapters/tise_0.qmd


    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: id
format:
  orange-book-typst:
    keep-typ: true
    fontsize: "12pt"



