---
title: A Sample Article Using `quarto-ieee` for IEEE Journal and Transactions
format:
  ieee-pdf:
    keep-tex: true
author:
  - id: dfolio
    name: David Folio
    affiliations:
      - name: INSA Centre Val de Loire
        department: Laboratoire Prisme
        city: Bourges
        country: France
        postal-code: 18800
      - name: Unknown affiliation
    orcid: 0000-0001-9430-6091
    email: david.folio@insa-cvl.fr
    url: https://dfolio.fr/
    membership: "Member, IEEE"
    attributes:
      corresponding: true
    photo: david-folio.png
    bio: |
      Use `IEEEbiography`  with figure as  option and
      the author name as the argument followed by the biography text.
  - name: John Doe
    affiliations: 
      - name: Anonymous University
    bio: |
      Use `IEEEbiographynophoto` and the author name
      as the argument followed by the biography text.
    note: "Template created June 23, 2023; revised `r format(Sys.Date(),format='%B %d, %Y')`."
abstract: |
  This document describes the most common article elements and how to use the 
  `quarto-ieee` class with Pandoc/Quarto-Markdown to produce files that are
  suitable for submission to IEEE journals.  
  `quarto-ieee` can produce conference, journal, and technical note (correspondence) 
  papers with a suitable choice of class options. 
  It intends to generate PDF and HTML outputs that closely mimick what IEEE would generate.
keywords: [IEEE, IEEEtran, journal, Quarto, Pandoc, template]
#funding: 
funding: 
  statement: "The `quarto-ieee` template is freely available under the MIT license on github: <https://github.com/dfolio/quarto-ieee>."
pageheader:
  left: Journal XXX, Month Year
  right: 'D. Folio:  A Sample Article Using quarto-ieee'
bibliography: bibliography.bib
date: 2023-06-23
pdf: https://github.com/dfolio/quarto-ieee/blob/main/template.pdf
citation: 
  container-title: GitHUB
  page: 1-3
  type: software
  issued: 2023-06-23
  url: https://github.com/dfolio/quarto-ieee
  pdf-url: https://github.com/dfolio/quarto-ieee/template.pdf
---

# Introduction {#sec-intro}

[T]{.IEEEPARstart}[his]{}
file is intended to serve as a "sample article file"
for IEEE journal papers produced with (Pandoc/Quarto)-Markdown using `IEEEtran.cls` version 1.8b and later for the PDF output. 
It is based on `bare_jrnl_new_sample4.tex` provided by IEEE Publication Technology, Staff and available from  <https://template-selector.ieee.org/>.
The most common elements are covered in the simplified and updated instructions in `New_IEEEtran_how-to.pdf`.
For less common elements you can refer back to the original `IEEEtran_HOWTO.pdf`. 
It is assumed that the reader has a basic working knowledge of {{< latex >}} @mittelbach2023latex and of (Pandoc/Quarto)-Markdown [@MacFarlane_Pandoc; @Allaire_Quarto_2022] markup.


# The Design, Intent, and Limitations of this Templates

The `quarto-ieee` template is intended to **approximate the final look and page length of the articles/papers** either in PDF output or HTML output. 
**They are NOT intended to be the final produced work that is displayed in print or on IEEEXplore^®^**.
They will help to give the authors an approximation of the number of pages and layout that will be in the final version. 

## Unsuported feature and limitations
Although most of the {{< latex >}} and `IEEEtran.cls` commands and environment are supported, 
there are some limitations when trying to export to a format other than PDF  (e.g. HTML output).
For PDF output, the reader can use the {{< latex >}} command directly. However, this may break other output formats.
\
It can be can reported the following limitations of the  `quarto-ieee` template:
- Several authors with same affiliation produce weird output. 
  In such case, it is recommended to use `note` and `tex-author-no-affiliation: true`.
- For `PDF` output
  - `quarto-ieee` use a hack to handle the `longtable` issue with  2-column {{< latex >}} documents[^issues-1023].
    But, in some cases, a page overflow may occur (see also @sec-tables).
- For `HTML` output
  - The default Quarto toc is used, so the table of contents (toc) display is not the same as on [IEEEXplore<sup>®</sup>].
  - Footnote are put at the end of document, while on [IEEEXplore<sup>®</sup>] there are placed in the accordion.
  - Figures are not placed in the accordion.
  - [IEEEXplore<sup>®</sup>] specifics (e.g. citation metrics, etc.)
  - The `HTML` output is a  Quarto citeable article @quarto-citation, so a citation appendix is automatically added to the article end.
  
