book:
  author: Armein Z. R. Langi
  chapters:
  - index.qmd
  - part: P1/p1.qmd
    chapters:
    - P1/c01.qmd
    - P1/c02.qmd
    - P1/c03.qmd
    - P1/c04.qmd
  - part: P2/p2.qmd
    chapters:
    - P2/c05.qmd
    - P2/c06.qmd
    - P2/c07.qmd
    - P2/c08.qmd
  - part: P3/p3.qmd
    chapters:
    - P3/c09.qmd
    - P3/c10.qmd
    - P3/c11.qmd
  - part: P4/p4.qmd
    chapters:
    - P4/c12.qmd

  subtitle: Arsitektur dan Metoda
  title: Rekayasa Sistem Cerdas
project:
  type: book

bibliography: references.bib

lang: id
theme: fancy
tufte: false
buka-kanan: true
margin-alternatif: true

seri: "Seri TISE Triune Intelligence Smart Engineering"
institusi: "Institut Teknologi Bandung"

format:
  bookly-typst:
    keep-typ: true
    papersize: "iso-b5"
    include-in-header: "in_header.typ"
    include-before-body: "in_before.typ"
    include-after-body: "in_after.typ"
