project:
  type: book

book:
  title: "Buku DNA TISE level 5"
  subtitle: "Monograf Template untuk Rekayasawan, Stakeholder, dan Agents"
  author: "Armein Z. R. Langi"
  chapters:
    - index.qmd
    - chapters/part-1.qmd
    - chapters/02-tise-level-5.qmd
    - chapters/03-matrix-mission-mos7.qmd
    - chapters/04-workflow-full-scale.qmd
    - chapters/part-2.qmd
    - chapters/05-tise-level-4.qmd
    - chapters/part-3.qmd
    - chapters/06-tise-level-3.qmd
    - chapters/part-4.qmd
    - chapters/07-tise-level-2.qmd
    - chapters/part-5.qmd
    - chapters/08-tise-level-1.qmd
    - chapters/part-6.qmd
    - chapters/09-tise-level-0.qmd
    - chapters/10-summary-what-next.qmd
  appendices:
    - appendices/a-questions-level-5.qmd
    - appendices/b-questions-level-4.qmd
    - appendices/c-questions-level-3.qmd
    - appendices/d-questions-level-2.qmd
    - appendices/e-questions-level-1.qmd
    - appendices/f-questions-level-0.qmd
    - appendices/g-jawaban-ke-dokumen-dna.qmd
    - appendices/h-jawaban-ke-dokumen-akademik.qmd

bibliography: references.bib
link-citations: true
lang: id

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
  pdf:
    toc: true
    number-sections: true

execute:
  echo: false
