---
format:
    typst:
        columns: 2
        number-sections: false

---


## Verse 1
Look at the stars
Look how they shine for you
And everything you do
Yeah, they were all yellow

## Verse 2
I came along
I wrote a song for you
And all the things you do
And it was called yellow

## Verse 3
So, then I took my turn
Oh, what a thing to have done
And it was all yellow

## Chorus
Your skin, oh yeah, your skin, and bones
(Ooh) turn into something beautiful
(Ah) and you know, you know I love you so
You know I love you so

## Verse 4
I swam across
I jumped across for you
Oh, what a thing to do
'Cause you were all yellow

## Verse 5
I drew a line
I drew a line for you
Oh, what a thing to do
And it was all yellow

## Chorus
And your skin, oh yeah, your skin, and bones
(Ooh) turn into something beautiful
(Ah) and you know, for you, I'd bleed myself dry
For you, I'd bleed myself dry

## Bridge
It's true
Look how they shine for you
Look how they shine for you
Look how they shine for-

## Bridge
Look how they shine for you
Look how they shine for you
Look how they shine

## Verse 6
Look at the stars
Look how they shine for you
And all the things that you do