import yaml
import subprocess
import re

with open('_metadata.yml', 'r') as f:
    meta = yaml.safe_load(f)

title = meta.get('title', 'Paper Title')
authors = meta.get('authors', [])
abstract = meta.get('abstract', '')
keywords = meta.get('index-terms', [])

author_names = []
thanks_lines = []
for a in authors:
    name = a.get('name', '')
    author_names.append(name)
    affil_list = a.get('affiliations', [])
    if affil_list:
        affil = affil_list[0]
        dept = affil.get('department', '')
        inst = affil.get('name', '')
        city = affil.get('city', '')
        country = affil.get('country', '')
        email = a.get('email', '')
        thanks_lines.append(f"\\thanks{{{name} is with {dept}, {inst}, {city}, {country}. e-mail: {email}.}}")

author_str = "\\author{" + " and ".join(author_names)
if thanks_lines:
    author_str += "%\n" + "%\n".join(thanks_lines)
author_str += "}"

abstract_str = "\\begin{abstract}\n" + abstract.strip() + "\n\\end{abstract}"
keywords_str = "\\begin{IEEEkeywords}\n" + ", ".join(keywords) + "\n\\end{IEEEkeywords}"

print("Generating body.tex using pandoc...")
subprocess.run(['quarto', 'pandoc', 'healthy.qmd', '-t', 'latex', '--natbib', '-o', 'body.tex'])

with open('body.tex', 'r') as f:
    body = f.read()

# We might want to remove the markdown `# Introduction` from the pandoc output
# if the IEEE template already has `\section{Introduction}`, but actually we can
# just replace everything from `\section{Introduction}` in the template with the 
# body generated by pandoc, which contains `\section{Introduction}`.

with open('ieee.tex', 'r') as f:
    ieee = f.read()

# Replace title
ieee = re.sub(r'\\title\{Bare Demo of IEEEtran\.cls\\\\ for IEEE Journals\}', lambda m: f'\\\\title{{{title}}}', ieee)

# Replace authors block
author_regex = r'\\author\{Michael~Shell,.*?(?=\\markboth\{)'
ieee = re.sub(author_regex, lambda m: author_str + "\n\n", ieee, flags=re.DOTALL)

# Replace abstract
ieee = re.sub(r'\\begin\{abstract\}.*?\\end\{abstract\}', lambda m: abstract_str, ieee, flags=re.DOTALL)

# Replace keywords
ieee = re.sub(r'\\begin\{IEEEkeywords\}.*?\\end\{IEEEkeywords\}', lambda m: keywords_str, ieee, flags=re.DOTALL)

# Add necessary packages
packages = """
\\usepackage{longtable}
\\usepackage{booktabs}
\\usepackage{array}
\\usepackage{calc}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{amsmath}
\\usepackage{multirow}
"""
ieee = ieee.replace('\\begin{document}', packages + '\n\\begin{document}')

# Extract everything before \section{Introduction}
header_match = re.search(r'(.*?)\\section\{Introduction\}', ieee, flags=re.DOTALL)
if header_match:
    header = header_match.group(1)
else:
    header = ieee

footer_match = re.search(r'\\end\{document\}', ieee)
if footer_match:
    footer = "\\end{document}\n"
else:
    footer = "\\end{document}\n"

# Fix figure references in body and citations
body = "\\providecommand{\\tightlist}{\\setlength{\\itemsep}{0pt}\\setlength{\\parskip}{0pt}}\n" + body
body = body.replace('\\citep{', '\\cite{')
body = body.replace('\\citet{', '\\cite{')
body = re.sub(r'\\pandocbounded\{\\includegraphics\[.*?\]\{(.*?)\}\}', r'\\includegraphics[width=\\columnwidth]{\1}', body)

# Append bibliography
body += "\n\n\\bibliographystyle{IEEEtran}\n\\bibliography{references}\n"

new_ieee = header + body + footer

with open('draft.tex', 'w') as f:
    f.write(new_ieee)

print("draft.tex generated successfully.")
