project:
  type: book
  output-dir: _book

book:
  title: "Rekayasa Sistem Cerdas"
  subtitle: "Arsitektur dan Representasi Pengetahuan"
  author: "Armein Z. R. Langi"
  chapters:
    - index.qmd
    - part: bagian1.qmd
      chapters:
        - 01-konsep-inti-ontologi.qmd
    - part: bagian2.qmd
      chapters:
        - 02-metodologi-multi-domain-picoc.qmd
    - part: bagian3.qmd
      chapters:
        - 03-integrasi-teknologi.qmd
    - part: bagian4.qmd
      chapters:
        - 04-studi-kasus.qmd

bibliography: references.bib
lang: id
tufte: false
buka-kanan: true
margin-alternatif: true

seri: "Seri TISE Triune Intelligence Smart Engineering"
institusi: "Institut Teknologi Bandung"

format:
  bookly-typst:
    keep-typ: true
    papersize: "iso-b5"
    include-in-header: "in_header.typ"
    include-before-body: "in_before.typ"
    include-after-body: "in_after.typ"