book:
  author: Armein Z. R. Langi
  chapters:
  - index.qmd
  - intro.qmd
  - part: P1/P1.qmd
    chapters:
    - P1/ch-01.qmd
  - part: P2/P2.qmd
    chapters:
    - P2/ch-02.qmd
    - P2/ch-03.qmd
  - part: P3/P3.qmd
    chapters:
    - P3/ch-04.qmd
    - P3/ch-05.qmd
  - part: P4/P4.qmd
    chapters:
    - P4/ch-06.qmd
    - P4/ch-07.qmd
  - part: P5/P5.qmd
    chapters:
    - P5/ch-08.qmd
    - P5/ch-09.qmd
    - P5/ch-10.qmd
    - P5/ch-11.qmd
  - part: P6/P6.qmd
    chapters:
    - P6/ch-12.qmd
    - P6/ch-13.qmd
    - P6/ch-14.qmd
    - P6/ch-15.qmd
    - P6/ch-16.qmd
    - P6/ch-17.qmd
  - part: backmatter.qmd
    chapters:
    - references.qmd
  subtitle: Arsitektur dan Representasi Pengetahuan
  title: Rekayasa Sistem Cerdas
project:
  type: book
format:
  typst:
    keep-typ: true
