project:
  type: book

book:
  title: "Judul"
  subtitle: "Subjudul"
  author: "Armein Z. R. Langi"
  date: "09/04/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: id
logo: logo.png
format:
  typst:
    keep-typ: true
    papersize: "iso-b5"
    include-in-header: header.typ
    include-after-body: afterbody.typ
    include-before-body: beforebody.typ

    



