project:
  type: book
  output-dir: _book

book:
  title: "Triune-Intelligence Smart-Engineering"
  subtitle: "Rekayasa untuk Kemanusiaan di era Artificial Intelligence"
  author: "Armein Z. R. Langi"
  language: id
  chapters:
    - index.qmd
    - chapters/bab-01.qmd
    - part: chapters/part-01.qmd
      chapters:
        - chapters/bab-02.qmd
        - chapters/bab-03.qmd
        - chapters/bab-04.qmd
    - part: chapters/part-02.qmd
      chapters:
        - chapters/bab-05.qmd
        - chapters/bab-06.qmd
    - part: chapters/part-03.qmd
      chapters:
        - chapters/bab-07.qmd
        - chapters/bab-08.qmd
    - part: chapters/part-04.qmd
      chapters:
        - chapters/bab-09.qmd
        - chapters/bab-10.qmd
    - part: chapters/part-05.qmd
      chapters:
        - chapters/bab-11.qmd
        - chapters/bab-12.qmd
    - part: chapters/part-06.qmd
      chapters:
        - chapters/bab-13.qmd
        - chapters/bab-14.qmd
        - chapters/bab-15.qmd
  appendices: 
    - chapters/lampiran-a.qmd

lang: id
format:
  typst:
    papersize: "a4"
    toc: true
    number-sections: true
    include-in-header: "in_header.typ"
    include-before-body: "in_before.typ"
    include-after-body: "in_after.typ"
bibliography: references.bib
link-citations: true
